site_name: cookiecutter-hydro
repo_url: https://github.com/zawadzkim/cookiecutter-hydro
site_url: https://zawadzkim.github.io/cookiecutter-hydro
site_description: A cookiecutter template for structuring hydrological modelling projects using Python with Poetry as dependency management tool.
site_author: Mateusz Zawadzki
edit_uri: edit/main/docs/
repo_name: zawadzkim/cookiecutter-hydro
copyright: Maintained by <a href="https://zawadzkim.com">Mateusz</a>.

nav:
  - Home: index.md
  - Features:
      - CI/CD with Github Actions: features/cicd.md
      - Linting & code quality: features/linting.md
      - Makefile: features/makefile.md
      - Dependency management with Poetry: features/poetry.md
      - Testing with Pytest: features/pytest.md
      - Containerization with Docker: features/docker.md
      - Devcontainer with VSCode: features/devcontainer.md
  - Tutorial: tutorial.md
  - Prompt Arguments: prompt_arguments.md
plugins:
  - search
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zawadzkim/cookiecutter-hydro
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cookiecutter-hydro/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
