[project]
name = "{{cookiecutter.project_slug}}"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.11,<3.13"
{% if cookiecutter.jupyter == 'y' -%}
jupyter = "*"
ipykernel = "*"
{% endif -%}

[pypi-dependencies]
{{cookiecutter.project_slug}} = { path = ".", editable = true }
pytest = ">=7.2,<9"
mypy = ">=1.5,<2"
ruff = ">=0.5,<1"
{% if cookiecutter.model == 'flopy' -%}
flopy = ">=3.8,<4"
{% elif cookiecutter.model == 'swap' -%}
pyswap = "*"
simplesoilprofile = "*"
{% elif cookiecutter.model == 'pastas' -%}
pastas = ">=1.7,<2"
{% endif -%}
{% if cookiecutter.gensor == 'y' -%}
gensor = "*"
{% endif -%}

[tasks]
test = "python -m pytest --doctest-modules tests"
type-check = "mypy"
lint = "ruff check src"

[tasks.all]
depends-on = ["lint", "type-check", "test"]
